services:
  - type: pserv
    name: cropcloud-api
    env: node
    plan: free
    repo: https://github.com/HarshaVardhan2709/CROPCLOUDV2-MAIN
    branch: master
    buildCommand: npm install -g pnpm && pnpm install && pnpm exec prisma generate && pnpm build
    startCommand: cd apps/api && node dist/main.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: DATABASE_URL
        sync: false
      - key: JWT_ACCESS_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
